### ISSUE TITLE
Grunt Server Error, fresh install (coffeescript)

### ISSUE THREAD

**Issue by lukeed** [yeoman/generator-ember#217]
Hey all,

Just installed a fresh copy of Ember using the --coffee flag.

Immediately upon running `grunt server` I'm given the issue below. 
The server will run if i `--force` it too, but that doesn't seem ideal.

Ideas?

    .../ember-cms/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
    throw err;
          ^
    TypeError: Cannot call method '_format' of undefined
    at Log.header (/ember-cms/node_modules/grunt/node_modules/grunt-legacy-log/index.js:217:18)
    at process.<anonymous> (/ember-cms/node_modules/time-grunt/time-grunt.js:36:3)
    at process.EventEmitter.emit (events.js:117:20)
    at process.exit (node.js:707:17)
    at tryToExit (/ember-cms/node_modules/grunt/node_modules/exit/lib/exit.js:17:15)
    at Object.exit (/ember-cms/node_modules/grunt/node_modules/exit/lib/exit.js:34:3)
    at Object.fail.warn (/ember-cms/node_modules/grunt/lib/grunt/fail.js:73:16)
    at /ember-cms/node_modules/grunt-concurrent/tasks/concurrent.js:26:12
    at callDone (/ember-cms/node_modules/grunt/node_modules/grunt-legacy-util/index.js:159:5)
    at ChildProcess.<anonymous> (/ember-cms/node_modules/grunt/node_modules/grunt-legacy-util/index.js:198:5)

**Comment by sindresorhus** [comment]
This generator has been deprecated in favor of ember-cli: https://github.com/yeoman/generator-ember/issues/249

It has been lacking an active maintainer for a long time and the Ember community is strongly behind ember-cli.
